#! /bin/bash
files=`ls "${1}"`

if [ $# -lt 2 ]; then
	echo "Usage :"
	echo "    addframe <filename> <output_directory>"
	echo "        filename : you can use wildcards."
	echo "        output_directory_path : output directory path name"
	exit 0
fi

if [ ! -d ${2} ]; then
	echo "Not found directory!! Specify an existing directory."
	exit 1
fi

addExifData() { # {{{
	make=`exiftool -s -Make -T $1`
	camera=`exiftool -s -Model -T $1`
	lens=`exiftool -s -LensModel -T $1`
	if [ "${lens}" == "" -o "${lens}" == "-" ]; then
		lens=`exiftool -s -LensID -T $1`
	fi
	iso=`exiftool -s -ISO -T $1`
	fnumber=`exiftool -s -FNumber -T $1`
	ss=`exiftool -s -ShutterSpeed -T $1`
	font=Noto-Sans-CJK-JP

	convert tmp2.webp \
			-pointsize "24" \
			-font ${font} \
			-fill black \
			-gravity south \
			-annotate +0+64 "Shot on ${camera}" \
			-quality 100 \
			- | \
	convert - \
			-font ${font} \
			-pointsize "16" \
			-fill black \
			-gravity south \
			-annotate +0+40 "${make}" \
			-quality 100 \
			- | \
	convert - \
			-font ${font} \
			-pointsize "16" \
			-fill "#838383" \
			-gravity south \
			-annotate +0+16 "$lens f${fnumber} ${ss}s ISO${iso}" \
			-quality 100 \
			${2}"/"${1}
	rm tmp2.webp
} # }}}

rotateImage() { # {{{
	orient=`exiftool -s -Orientation -T "${1}"`
	flg=`expr "${orient}" : "^Rotate"`
	if [ ${flg} -ne 0 ]; then
		angle=`echo ${orient} | cut -d " " -f 2`
		convert "${1}" -rotate "${angle}" -orient undefined -quality 100 tmp1.webp
	else
		convert "${1}" -quality 100 tmp1.webp
	fi
} # }}}

addframe() { # {{{
	length="1280"	# 画像長辺サイズ
	top="32"		# 上辺幅
	left="32"		# 左辺幅
	right="32"		# 右辺幅
	bottom="128"	# 下辺幅

	width=`identify -format '%w' tmp1.webp`
	height=`identify -format '%h' tmp1.webp`
	if [ $width -gt $height ]; then
		convert tmp1.webp \
			-resize "${length}x" \
			-mattecolor "#fff" \
			-splice ${left}x${top} \
			-quality 100 - | \
		convert - \
			-gravity southeast \
			-mattecolor "#fff" \
			-splice ${right}x${bottom} \
			-quality 100 tmp2.webp
		rm tmp1.webp
	else
		convert tmp1.webp \
			-resize "x${length}" \
			-mattecolor "#fff" \
			-splice ${left}x${top} \
			-quality 100 - | \
		convert - \
			-gravity southeast \
			-mattecolor "#fff" \
			-splice ${right}x${bottom} \
			-quality 100 tmp2.webp
		rm tmp1.webp
	fi
} # }}}

for tfile in ${files}
do
	echo "Just a second..."
	# 回転情報含有時処理 output tmp1.webp
	rotateImage "${tfile}"

	# フレーム付加 output tmp2.webp
	addframe

	# Exif データ貼り付け
	addExifData "${tfile}" "${2}"

	echo "Done!!"
done

