#! /bin/bash
inpath=`ls "${1}"`
outpath=`ls "${2}"`

if [ $# -lt 2 ]; then
	echo "Usage :"
	echo "    addframe <filename> <output_directory>"
	echo "        filename : you can use wildcards."
	echo "        output_directory_path : output directory path name"
	exit 0
fi

if [ ! -d ${2} ]; then
	echo "Not found directory!! Specify an existing directory."
	exit 1
fi

rotateImage() { # {{{
	#data=$(exiftool -s -T -Orientation -ImageWidth -ImageHeight -Model -Make  -LensModel -LensID -FNumber -ShutterSpeed -ISO "${tfile}" | column -d -s "\t")
	length="1280"	# 画像長辺サイズ
	top="32"		# 上辺幅
	left="32"		# 左辺幅
	right="32"		# 右辺幅
	bottom="128"	# 下辺幅

	width=$(echo "${1}" | cut -f 2)
	height=$(echo "${1}" | cut -f 3)
	orient=$(echo "${1}" | cut -f 1)
	flg=`expr "${orient}" : "Rotate"`
	ext=${2##*.}
	if  [ "${ext}" != "HEIC" ]; then
		if [ ${flg} -eq 0 ] ; then
			if [ ${width} -gt ${height} ];then
				magick convert "${2}" -resize ${length}x -quality 100 /tmp/work/tmp2.webp
			else
				magick convert "${2}" -resize x${length} -quality 100  /tmp/work/tmp2.webp
			fi
		else
			if [ ${width} -gt ${height} ];then
				magick convert "${2}" -auto-orient -quality 100 webp:- | magick convert - -resize x${length} -quality 100 /tmp/work/tmp2.webp
			else
				magick convert "${2}" -auto-orient -quality 100 webp:- | magick convert - -resize ${length}x -quality 100 /tmp/work/tmp2.webp
			fi
		fi
	else
		if [ ${flg} -eq 0 ] ; then
			magick convert "${2}" -auto-orient -quality 100 webp:- | magick convert - -resize ${length}x -quality 100 /tmp/work/tmp2.webp
		else
			magick convert "${2}" -auto-orient -quality 100 webp:- | magick convert - -resize x${length} -quality 100 /tmp/work/tmp2.webp
		fi
	fi
} # }}}

createFrame() { #{{{
	#data=$(exiftool -s -T -Orientation -ImageWidth -ImageHeight -Model -Make  -LensModel -LensID -FNumber -ShutterSpeed -ISO "${tfile}" | column -d -s "\t")
	length="1280"	# 画像長辺サイズ
	top="32"		# 上辺幅
	left="32"		# 左辺幅
	right="32"		# 右辺幅
	bottom="128"	# 下辺幅
	font=Noto-Sans-CJK-JP

	orient=$(echo "${1}" | cut -f 1)
	width=$(echo "${1}" | cut -f 2)
	height=$(echo "${1}" | cut -f 3)
	camera=$(echo "${1}" | cut -f 4)
	make=$(echo "${1}" | cut -f 5)
	lens=$(echo "${1}" | cut -f 6)
	if [ "${lens}" == "" -o "${lens}" == "-" ]; then
		lens=$(echo "${1}" | cut -f 7)
	fi
	fnumber=$(echo "${1}" | cut -f 8)
	ss=$(echo "${1}" | cut -f 9)
	iso=$(echo "${1}" | cut -f 10)
	tmpH=$(expr ${height} "*" 1280 "/" ${width})
	tmpW=$(expr ${width} "*" 1280 "/" ${height})
	flg=`expr "${orient}" : "Rotate"`
	if [ ${flg} -eq 0 ]; then
		if [ ${width} -gt ${height} ];then
			w=$(expr 1280 + ${left} + ${right})
			h=$(expr ${tmpH} + ${top} + ${bottom})
		else
			w=$(expr ${tmpW} + ${left} + ${right})
			h=$(expr 1280 + ${top} + ${bottom})
		fi
	else
		w=$(expr ${tmpH} + ${left} + ${right})
		h=$(expr 1280 + ${top} + ${bottom})
	fi
	magick convert -size ${w}x${h} xc:#ffffff webp:- |
	magick convert - \
			-pointsize "24" \
			-font ${font} \
			-fill black \
			-gravity south \
			-annotate +0+64 "Shot on ${camera}" \
			-quality 100 \
			- | \
	magick convert - \
			-font ${font} \
			-pointsize "16" \
			-fill black \
			-gravity south \
			-annotate +0+40 "${make}" \
			-quality 100 \
			- | \
	magick convert - \
			-font ${font} \
			-pointsize "16" \
			-fill "#838383" \
			-gravity south \
			-annotate +0+16 "$lens f${fnumber} ${ss}s ISO${iso}" \
			-quality 100 \
			/tmp/work/tmp1.webp
} # }}}

mergeImage() { # {{{
	magick convert /tmp/work/tmp1.webp /tmp/work/tmp2.webp -gravity north -geometry +0+32 -compose over -composite "${2}""/""${1}"
	rm /tmp/work/tmp1.webp /tmp/work/tmp2.webp
} # }}}

echo "Just a second..."

if [ ! -d "/tmp/work" ] ; then
	mkdir -p /tmp/work
fi

data=$(exiftool -s -T -Orientation -ImageWidth -ImageHeight -Model -Make  -LensModel -LensID -FNumber -ShutterSpeed -ISO "${1}" | column -d -s "\t")
echo "createFrame"
createFrame "${data}"

echo "rotateImage"
rotateImage "${data}" "${1}"

echo "mergeImage"
fname=`basename "${1}"`
mergeImage  "${fname}" ${2}

echo "Done!!"

