name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.*'

      - name: Build for ${{ matrix.os }}
        run: |
          mkdir -p artifacts/${{ matrix.os }}
          if [ ${{ matrix.os }} = 'ubuntu-latest' ]; then
            GOOS=linux GOARCH=amd64 go build -o artifacts/${{ matrix.os }}/addframe-linux
            GOOS=windows GOARCH=amd64 go build -o artifacts/${{ matrix.os }}/addframe.exe
          elif [ ${{ matrix.os }} = 'macos-latest' ]; then
            GOOS=darwin GOARCH=amd64 go build -o artifacts/${{ matrix.os }}/addframe_amd64
            GOOS=darwin GOARCH=arm64 go build -o artifacts/${{ matrix.os }}/addframe_arm64
            lipo -create -output artifacts/${{ matrix.os }}/addframe-macos artifacts/${{ matrix.os }}/addframe_amd64 artifacts/${{ matrix.os }}/addframe_arm64
            rm artifacts/${{ matrix.os }}/addframe_amd64 artifacts/${{ matrix.os }}/addframe_arm64
          fi
        shell: bash

      - name: Copy addframe.json
        run: cp addframe.json artifacts/${{ matrix.os }}/
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: artifacts/${{ matrix.os }}

  zip:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List build artifacts
        run: ls -la ./artifacts
        shell: bash

      - name: Create ZIP file
        run: |
          mkdir -p artifacts/zipped
          cd artifacts
          zip -r zipped/addframe-linux.zip ubuntu-latest/addframe-linux ubuntu-latest/addframe.json
          zip -r zipped/addframe-macos.zip macos-latest/addframe-macos macos-latest/addframe.json
          zip -r zipped/addframe-windows.zip ubuntu-latest/addframe.exe ubuntu-latest/addframe.json
        shell: bash

      - name: Upload ZIP files
        uses: actions/upload-artifact@v4
        with:
          name: zipped-artifacts
          path: artifacts/zipped/

  release:
    needs: zip
    runs-on: ubuntu-latest
    steps:
      - name: Download ZIP files
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/zipped

      - name: List downloaded artifacts
        run: ls -la ./artifacts/zipped

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/zipped/addframe-linux.zip
            ./artifacts/zipped/addframe-macos.zip
            ./artifacts/zipped/addframe-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
