name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.*'

      - name: Build for ${{ matrix.os }}
        run: |
          mkdir -p artifacts
          case ${{ matrix.os }} in
            ubuntu-latest)
              go build -o artifacts/addframe-linux
              ;;
            windows-latest)
              go build -o artifacts/addframe.exe
              ;;
            macos-latest)
              go build -o artifacts/addframe
              ;;
          esac

      - name: List build artifacts
        run: ls -la artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: addframe-${{ matrix.os }}
          path: artifacts/${{ matrix.os == 'windows-latest' && 'addframe.exe' || (matrix.os == 'ubuntu-latest' && 'addframe-linux' || 'addframe') }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List downloaded artifacts
        run: ls -la ./artifacts/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/addframe-linux
            ./artifacts/addframe.exe
            ./artifacts/addframe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
