name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.*'

      - name: Build for ${{ matrix.os }}
        run: |
          mkdir -p artifacts/${{ matrix.os }}
          if [ ${{ matrix.os }} = 'ubuntu-latest' ]; then
            GOOS=linux GOARCH=amd64 go build -o artifacts/${{ matrix.os }}/addframe-linux
            GOOS=windows GOARCH=amd64 go build -o artifacts/${{ matrix.os }}/addframe.exe
          elif [ ${{ matrix.os }} = 'macos-latest' ]; then
            GOOS=darwin GOARCH=amd64 go build -o artifacts/${{ matrix.os }}/addframe_amd64
            GOOS=darwin GOARCH=arm64 go build -o artifacts/${{ matrix.os }}/addframe_arm64
            lipo -create -output artifacts/${{ matrix.os }}/addframe-macos artifacts/${{ matrix.os }}/addframe_amd64 artifacts/${{ matrix.os }}/addframe_arm64
            rm artifacts/${{ matrix.os }}/addframe_amd64 artifacts/${{ matrix.os }}/addframe_arm64
          elif [ ${{ matrix.os }} = 'windows-latest' ]; then
            GOOS=windows GOARCH=amd64 go build -o artifacts/${{ matrix.os }}/addframe.exe
          fi
          # Verify that the files are created
          ls -la artifacts/${{ matrix.os }}
        shell: bash

      - name: Copy addframe.json
        run: cp addframe.json artifacts/${{ matrix.os }}/
        shell: bash

      - name: Create ZIP file for Linux and macOS
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          cd artifacts/${{ matrix.os }}
          ls -la # Verify the files exist before zipping
          if [ ${{ matrix.os }} = 'ubuntu-latest' ]; then
            zip addframe-linux.zip addframe-linux addframe.json
          elif [ ${{ matrix.os }} = 'macos-latest' ]; then
            zip addframe-macos.zip addframe-macos addframe.json
          fi
        shell: bash

      - name: Create ZIP file for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd artifacts/windows-latest
          ls -la # Verify the files exist before zipping
          powershell -Command "Compress-Archive -Path 'addframe.exe', 'addframe.json' -DestinationPath 'addframe-windows.zip'"
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: addframe-${{ matrix.os }}
          path: artifacts/${{ matrix.os }}/addframe-${{ matrix.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List downloaded artifacts
        run: ls -la ./artifacts/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/addframe-macos-latest/addframe-macos.zip
            ./artifacts/addframe-ubuntu-latest/addframe-linux.zip
            ./artifacts/addframe-windows-latest/addframe-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
