name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.*'

      - name: Build for ${{ matrix.os }}
        run: |
          mkdir -p artifacts/${{ matrix.os }}
          case ${{ matrix.os }} in
            ubuntu-latest)
              GOOS=linux GOARCH=amd64 go build -o artifacts/${{ matrix.os }}/addframe-linux
              ;;
            windows-latest)
              GOOS=windows GOARCH=amd64 go build -o artifacts/${{ matrix.os }}/addframe.exe
              ;;
            macos-latest)
              GOOS=darwin GOARCH=amd64 go build -o artifacts/${{ matrix.os }}/addframe_amd64
              GOOS=darwin GOARCH=arm64 go build -o artifacts/${{ matrix.os }}/addframe_arm64
              lipo -create -output artifacts/${{ matrix.os }}/addframe-macos artifacts/${{ matrix.os }}/addframe_amd64 artifacts/${{ matrix.os }}/addframe_arm64
              rm artifacts/${{ matrix.os }}/addframe_amd64 artifacts/${{ matrix.os }}/addframe_arm64
              ;;
          esac

      - name: List build artifacts
        run: ls -la artifacts/

      - name: Copy addframe.json
        run: cp addframe.json artifacts/${{ matrix.os }}/

      - name: Create ZIP file
        run: |
          cd artifacts/${{ matrix.os }}
          zip addframe-${{ matrix.os }}.zip addframe* addframe.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: addframe-${{ matrix.os }}
          path: artifacts/${{ matrix.os }}/addframe-${{ matrix.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest  # リリースジョブはUbuntu上で実行
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List downloaded artifacts
        run: ls -la ./artifacts/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/addframe-macos-latest/addframe-macos.zip
            ./artifacts/addframe-windows-latest/addframe-windows-latest.zip
            ./artifacts/addframe-ubuntu-latest/addframe-linux-latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
